apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: mynode-app
build:
  artifacts:
  - image: matharoo89/mynode-app
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/mynode-ingress.yaml
    - k8s/service.yaml
